spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: developer
    password: Developer@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create

  mail:
    host: smtp.gmail.com
    port: 587
    username: XXXXXXX
    password: XXXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail_on_empty_beans: false



